### PR TITLE
Mocha support

### PR DESCRIPTION
**Pull request by adamjmcgrath**

### CODE REVIEW

**Comment by albertjan** [comment]
Thanks! :smile:

I just tried it but I'm getting this error:

```js
ReferenceError: QUnit is not defined
    at assets/test-support.js:6284:16
    at mod.state (assets/vendor.js:150:29)
    at tryFinally (assets/vendor.js:30:14)
    at requireModule (assets/vendor.js:148:5)
    at s (assets/test-support.js:1686:142)
    at s (assets/test-support.js:1686:122)
    at requireFrom (assets/vendor.js:121:12)
    at reify (assets/vendor.js:106:22)
    at mod.state (assets/vendor.js:149:17)
    at tryFinally (assets/vendor.js:30:14)
```

**Comment by adamjmcgrath** [comment]
No worries - will double check that issue

**Comment by albertjan** [comment]
Oh wait testem.json isn't automatically updated by `ember-cli-mocha`. Wouldn't it be better to look for that package in `package.json`?

**Comment by albertjan** [comment]
After I set the testem.json framework to `mocha` it worked! Nice work.

**Comment by adamjmcgrath** [comment]
Cool - am happy to change the framework detection to checking for `ember-cli-mocha` in the package.json if you think that would be better.

**Comment by albertjan** [comment]
It's a bit more fool proof.

**Comment by adamjmcgrath** [comment]
Yeah, make sense - will update

**Comment by albertjan** [comment]
Awesome thank you very much!

**Comment by adamjmcgrath** [comment]
no problem :)

**Comment by albertjan** [comment]
pushed a new version to npm

**Comment by adamjmcgrath** [comment]
Thanks

**Pull request merged**
