### PR TITLE
let npm install yadda

### PR DESCRIPTION
**Pull request by albertjan**
add yadda as a dependency in package.json, otherwise it doesn't want to be installed.

### CODE REVIEW

**Comment by albertjan** [comment]
@sfbwalder keeping you in the loop 😄

**Comment by simonihmig** [comment]
But we have this line https://github.com/curit/ember-cli-yadda/blob/master/blueprints/main-index.js#L7 from #34. I guess both we be too much, right? :)

I was thinking including it just as a dep (not devDep) like in this PR would be enough, no need to force into the app's package.json. But I might miss something? /cc @sfbwalder

**Comment by albertjan** [comment]
The issue is if fails with an exception during install, apparently it needs yadda before that line happens. We could remove that line.

**Comment by albertjan** [comment]
```
➜  yadda-test git:(master) ember install curit/ember-cli-yadda
Installed packages for tooling via npm.
Cannot find module 'yadda'
Error: Cannot find module 'yadda'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/albertjan/yadda-test/node_modules/ember-cli-yadda/lib/feature-parser.js:4:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by albertjan** [comment]
This may be because the blueprint doesn't get run automatically. But I also don't see why we would want to specify a dependency in code rather then package.json.

**Comment by sfbwalder** [comment]
How will the consumer set what version of yadda they want to use with this change?

**Comment by albertjan** [comment]
they can still do the same thing with npm right:

```
npm uninstall yadda --save-dev
npm install yadda@{version} --save-dev
```

**Comment by albertjan** [comment]
@sfbwalder I set no version limitation in the package.json giving users the freedom to install their own version.

**Pull request merged**
