### PR TITLE
import destroyApp from consuming app

### PR DESCRIPTION
**Pull request by simonihmig**
`startApp` is imported form the consuming app, but not `destroyApp`, instead `Ember.run(this.application, 'destroy')` is called directly. When adding custom tear down logic into your `tests/helpers/destroy-app.js`  that will never be executed when using acceptance tests with ember-cli-yadda. This PR fixes this.

### CODE REVIEW

**Comment by albertjan** [comment]
Sweet 😄 thanks.

**Comment by albertjan** [comment]
We have two failing tests though.

**Comment by simonihmig** [comment]
Oh, sorry. Should have really checked that before... Will try to fix that!

**Comment by simonihmig** [comment]
It is failing because there is no `destroy-app.js` in the local tests/helpers folder. It is easy enough to add that (or update the used ember-cli to a more recent version that does include it by default), however I wonder how to handle that for the consuming app. 

If there are still apps out there that use ember-cli-yadda and are as well based on a very outdated ember-cli version that did not come with `destroy-app.js`, then this will break them as well, regardless of the addons tests failing or succeeding. 

Do you still want to support such older apps? And if so, how to handle this? Require them to add an `destroy-app.js`? Or generate the test code conditionally based on the existence of that file? (we could check this as the tests are generated in node-land)

**Comment by albertjan** [comment]
Lets investigate in which version of ember and ember-cli `destroy-app.js` was added.

**Comment by simonihmig** [comment]
Seems to be 1.13.10: https://github.com/ember-cli/ember-new-output/commits/59c9794ec3b9586e3de9f7a2654efa93eb69df0d/tests/helpers/destroy-app.js

**Comment by albertjan** [comment]
I'll have to look into updating ember-cli.

**Comment by albertjan** [comment]
do your tests pass if you do `npm install ember-cli@1.13.10`

**Comment by simonihmig** [comment]
I think it is not about updating the ember-cli dependency (which is in `node_modules`), but rather the missing `destroy-app.js` in https://github.com/curit/ember-cli-yadda/tree/master/tests/helpers. When updating ember-cli and running `ember init`, the app blueprints of ember-cli would create this missing file.

**Comment by simonihmig** [comment]
If you think it is ok to require the `destroy-app.js` file to exist in the consuming app (as it should be the case for every app scaffolded with an ember-cli release >= 1.13.10), I can add the missing files to this PR and make sure the tests are not failing.

**Comment by albertjan** [comment]
It seems better to me to run `ember init` with a `ember-cli@1.13.10` I'm ok with dropping support for 1.13.8 and 9

**Comment by albertjan** [comment]
awesome job! thank you for the PR 😄

**Pull request merged**
